name: Build Container

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}
jobs:
  build:
    concurrency:
      group: "build-container"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      attestations: write
      id-token: write
      contents: read
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Get Short SHA
        id: shortsha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build Container
        id: build
        run: |
          docker build --push -t ghcr.io/kingsukhoi/pg-container:${{ github.sha }} -t ghcr.io/kingsukhoi/pg-container:latest -t ghcr.io/kingsukhoi/pg-container:${{ steps.shortsha.outputs.sha_short }} .
          docker pull ghcr.io/${{github.repository}}:${{ github.sha }} > /dev/null
          echo "image_sha=$(docker image inspect ghcr.io/${{github.repository}}:${{ github.sha }} | jq '.[0].RepoDigests[0]' | cut -d ':' -f 2 | cut -d '"' -f 1)" >> $GITHUB_OUTPUT
      - name: test image sha
        run: |
          echo ${{steps.build.outputs.image_sha}}
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ghcr.io/${{github.repository}}
          subject-digest: "sha256:${{steps.build.outputs.image_sha}}"
          push-to-registry: true
